### ISSUE TITLE
Join Code For Miami Organization

### ISSUE THREAD

**Issue by abranhe** [Code-for-Miami/new_member_guide#2]
## Join Code For Miami Organization
Hi, I am living in Miami, & I am really excited about the active development and wanted to be a part of the Code for Miami organization on GitHub. I would love if somebody would add me to it

### Regards,
 _Abraham_.

**Comment by CyberStrike** [comment]
We are always happy to get new members, a merge or other significant contribution gets you an invite to the CFM Github Organisation. 

If you have any other questions [join our slack](http://cfm-invite.herokuapp.com/).

**Comment by abranhe** [comment]
I already joined the slack group ✅
