### ISSUE TITLE
Create a better member guide

### ISSUE THREAD

**Issue by HiGregory** [Code-for-Miami/new_member_guide#3]
We have a lot of members who come in but don't stick around. How can we make it easier to get involved in Code for Miami? Let's re-write the member guide with actionable steps for people to participate.

**Comment by RobertoJBeltran** [comment]
As a contributor, I would like to to feel less awkward touching the git history by maybe having some simple git guidelines that are cfm-wide

**Comment by HiGregory** [comment]
This is being started and led by @RobertoJBeltran 

See here. https://github.com/Code-for-Miami/cfm-meta-ux

Closing.
